### ISSUE TITLE
Dispatched event hasn't been initialized

### ISSUE THREAD

**Issue by CuiBenyong** [bolan9999/react-native-spring-scrollview#57]
开发环境 MAC os 10.15.1
运行环境 Android 真机（华为nova2s）
react-native 0.55.4
react-native-spring-scrollview 2.0.23
react-native-largelist-v3 3.0.15

代码：

_renderSection = (section: number) => {
    return (
        <View style={styles.section}>
            <Text>
                Section {section}
            </Text>
        </View>
    );
};

_renderIndexPath = ({ section: section, row: row }) => {
    return (
        <View style={styles.row}>
            <Text>
                Section {section} Row {row}
            </Text>
            <View style={styles.line} />
        </View>
    );
};

render() {
    const data = [];
    for (let section = 0; section < this._sectionCount; ++section) {
        const sContent = { items: [] };
        for (let row = 0; row < this._rowCount; ++row) {
            sContent.items.push(row);
        }
        data.push(sContent);
    }
    return (
        <LargeList
            style={styles.container}
            data={data}
            heightForSection={() => 50}
            renderSection={this._renderSection}
            heightForIndexPath={() => 50}
            renderIndexPath={this._renderIndexPath}
        />
    );
}
问题：

向上滑动闪退， 报错日志

2020-03-14 14:27:03.342 10321-10321/com.videogo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.videogo, PID: 10321
java.lang.AssertionError: Dispatched event hasn't been initialized
at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:114)
at com.bolan9999.SpringScrollView.sendOnScrollEvent(SpringScrollView.java:514)
at com.bolan9999.SpringScrollView.setContentOffset(SpringScrollView.java:477)
at com.bolan9999.SpringScrollView.moveToOffset(SpringScrollView.java:459)
at com.bolan9999.SpringScrollView.drag(SpringScrollView.java:403)
at com.bolan9999.SpringScrollView.onMove(SpringScrollView.java:142)
at com.bolan9999.SpringScrollView.onTouch(SpringScrollView.java:116)
at android.view.View.dispatchTouchEvent(View.java:11784)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:34)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
at android.app.Activity.dispatchTouchEvent(Activity.java:3559)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
at android.view.View.dispatchPointerEvent(View.java:12027)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5278)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5067)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4727)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4784)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7169)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7143)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7104)
2020-03-14 14:27:03.344 10321-10321/com.videogo E/AndroidRuntime: at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7325)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7248)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7353)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
at android.view.Choreographer.doCallbacks(Choreographer.java:790)
at android.view.Choreographer.doFrame(Choreographer.java:715)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7529)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by bolan9999** [comment]
Try the latest version,please.
